spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: postgres
    password: Ricsi.1324
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
backend:
  football:
    secretUser: football
    secretPass: foot123